---
# Simplify the workflow to isolate the YAML syntax error issue
name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Workflow simplified to isolate the problem"